window.CALENDAR_DATA = {
  {
  "generatedAt": "2026-07-07",
  "trip": {
    "start": "2026-10-09",
    "end": "2026-10-21",
    "departure": "2026-10-21",
    "timezone": "Asia/Tokyo",
    "baseCity": "Osaka",
    "assumption": "Trip year assumed to be 2026 because these dates are upcoming from the creation date."
  },
  "sources": [
    {
      "name": "Japan Gay Guide - Rainbow Festa Osaka",
      "url": "https://japangayguide.com/event/rainbow-festa-osaka/",
      "note": "2026 Osaka Pride/Rainbow Festa dates and venue."
    },
    {
      "name": "Rainbow Festa official site",
      "url": "https://rainbowfesta.org/",
      "note": "Official organizer site for Rainbow Festa and Kansai Rainbow Parade."
    },
    {
      "name": "FM802 MINAMI WHEEL official",
      "url": "https://minamiwheel.jp/teaser.php",
      "note": "Official 2026 MINAMI WHEEL teaser with dates and Shinsaibashi live-house format."
    },
    {
      "name": "Kyodo Osaka October 2026 calendar",
      "url": "https://kyodo-osaka.co.jp/calendar/202610",
      "note": "Month-level listings for concerts, theater, ballet, and ticketed performances."
    },
    {
      "name": "eplus Osaka October 2026 calendar",
      "url": "https://eplus.jp/sf/event/month-10/kansai/osaka",
      "note": "Ticketing source for exhibitions, interactive events, family shows, and concerts."
    },
    {
      "name": "Osaka Info - Kishiwada Danjiri Festival",
      "url": "https://osaka-info.jp/special/dc/event/detail749/",
      "note": "Official Osaka tourism listing for the October Kishiwada Danjiri dates."
    },
    {
      "name": "Osaka Convention and Tourism Bureau news",
      "url": "https://octb.osaka-info.jp/news_common/",
      "note": "Official notice for Osaka Fringe 2026 window."
    },
    {
      "name": "Kyoto City Official Travel Guide - Kyoto Music Expo",
      "url": "https://ja.kyoto.travel/event/single.php?event_id=5272",
      "note": "Official tourism listing for Kyoto Music Expo 2026."
    },
    {
      "name": "Nara City Tourism events",
      "url": "https://narashikanko.or.jp/event/",
      "note": "Official Nara City event calendar and detail pages."
    },
    {
      "name": "Nara Prefecture tourism event search",
      "url": "https://yamatoji.nara-kankou.or.jp/003events/?s=kana&ym=202610",
      "note": "Official Nara Prefecture month view."
    },
    {
      "name": "Billboard Live Osaka October 2026 schedule",
      "url": "https://www.billboard-live.com/osaka/schedules?month=2026-10-01",
      "note": "Official club schedule for Umeda Billboard Live Osaka."
    },
    {
      "name": "Universal Studios Japan 25th Anniversary official page",
      "url": "https://www.usj.co.jp/web/en/us/25th-anniversary-discover-u",
      "note": "Official USJ 25th-anniversary program running during the trip."
    },
    {
      "name": "Walkerplus Osaka October 2026",
      "url": "https://www.walkerplus.com/event_list/10/ar0727/",
      "note": "Aggregator used only for current 2026 Osaka listings visible on the 2026 page."
    }
  ],
  "events": [
    {
      "id": "rainbow-festa-2026",
      "title": "Rainbow Festa! 2026 / Osaka Pride Weekend",
      "dateStart": "2026-10-10",
      "dateEnd": "2026-10-11",
      "city": "Osaka",
      "area": "Ogimachi / Umeda",
      "venue": "Ogimachi Park",
      "time": "Oct 10 10:00-17:30; Oct 11 10:00-17:00",
      "category": "LGBTQ+ / Pride",
      "tags": [
        "pride",
        "parade weekend",
        "community",
        "festival",
        "free"
      ],
      "lgbtq": true,
      "cost": "Free admission",
      "status": "Confirmed by current source",
      "sourceName": "Japan Gay Guide + Rainbow Festa official",
      "sourceUrl": "https://japangayguide.com/event/rainbow-festa-osaka/",
      "description": "Kansai Rainbow Festa returns to Ogimachi Park with stage programming, booths, community groups, and Pride-weekend energy.",
      "tip": "Put this on the trip as a fixed anchor. It is the strongest confirmed LGBTQ+ event in the date range.",
      "priority": "top",
      "includeInIcs": true,
      "isOngoing": false,
      "programTbd": false,
      "lastVerified": "2026-07-07"
    },
    {
      "id": "kansai-rainbow-parade-20th",
      "title": "Kansai Rainbow Parade 2026 - 20th Anniversary",
      "dateStart": "2026-10-11",
      "dateEnd": "2026-10-11",
      "city": "Osaka",
      "area": "Ogimachi / Umeda",
      "venue": "Ogimachi Park and parade route TBA",
      "time": "Festival day; parade time/route TBA by organizer",
      "category": "LGBTQ+ / Pride",
      "tags": [
        "pride",
        "parade",
        "LGBTQ+",
        "free"
      ],
      "lgbtq": true,
      "cost": "Free",
      "status": "Confirmed by current source",
      "sourceName": "Japan Gay Guide + Rainbow Festa official",
      "sourceUrl": "https://japangayguide.com/event/rainbow-festa-osaka/",
      "description": "The Kansai Rainbow Parade celebrates its 20th anniversary during Rainbow Festa weekend.",
      "tip": "Check the official site again closer to October for route, lineup, and afterparty announcements.",
      "priority": "top",
      "includeInIcs": true,
      "isOngoing": false,
      "programTbd": false,
      "lastVerified": "2026-07-07"
    },
    {
      "id": "osaka-fringe-2026",
      "title": "Osaka Fringe 2026 / Osaka Culture Expo platform",
      "dateStart": "2026-10-09",
      "dateEnd": "2026-10-21",
      "city": "Osaka",
      "area": "Citywide",
      "venue": "Multiple venues",
      "time": "Festival window Oct 8-Nov 8; individual programme TBA",
      "category": "Arts Festival",
      "tags": [
        "arts",
        "open access",
        "citywide",
        "performances"
      ],
      "lgbtq": false,
      "cost": "Varies",
      "status": "Festival window confirmed; individual programme pending",
      "sourceName": "Osaka Convention and Tourism Bureau",
      "sourceUrl": "https://octb.osaka-info.jp/news_common/",
      "description": "A citywide open-access arts festival announced by the Osaka Convention and Tourism Bureau. Treat as a source to revisit once programme details publish.",
      "tip": "Because exact performances were not published yet, the site marks this as a platform rather than individual events.",
      "priority": "high",
      "includeInIcs": true,
      "isOngoing": true,
      "programTbd": true,
      "lastVerified": "2026-07-07"
    },
    {
      "id": "fm802-minami-wheel-2026",
      "title": "FM802 MINAMI WHEEL 2026",
      "dateStart": "2026-10-10",
      "dateEnd": "2026-10-12",
      "city": "Osaka",
      "area": "Shinsaibashi / Minami",
      "venue": "20+ live houses around Shinsaibashi",
      "time": "Three-day live-house circuit; lineup/times by pass schedule",
      "category": "Music Festival",
      "tags": [
        "music",
        "live houses",
        "indie",
        "rock",
        "Shinsaibashi"
      ],
      "lgbtq": false,
      "cost": "Ticket/pass required",
      "status": "Confirmed by current source",
      "sourceName": "FM802 MINAMI WHEEL official",
      "sourceUrl": "https://minamiwheel.jp/teaser.php",
      "description": "One of Osaka Minami's major live-house circuit festivals, spread across more than 20 venues.",
      "tip": "Pairs well with Rainbow Festa weekend if you want Pride daytime plus music at night.",
      "priority": "top",
      "includeInIcs": true,
      "isOngoing": false,
      "programTbd": false,
      "lastVerified": "2026-07-07"
    },
    {
      "id": "kishiwada-danjiri-october-2026",
      "title": "Kishiwada Danjiri Festival - October District Festival",
      "dateStart": "2026-10-10",
      "dateEnd": "2026-10-11",
      "city": "Osaka",
      "area": "Kishiwada / south Osaka",
      "venue": "East Kishiwada, Yagi, Yamataki and other district areas",
      "time": "Oct 10 eve festival; Oct 11 main festival",
      "category": "Traditional Festival",
      "tags": [
        "danjiri",
        "traditional",
        "parade",
        "festival"
      ],
      "lgbtq": false,
      "cost": "Free public viewing",
      "status": "Confirmed by current source",
      "sourceName": "Osaka Info official tourism",
      "sourceUrl": "https://osaka-info.jp/special/dc/event/detail749/",
      "description": "The October Kishiwada Danjiri festival covers multiple local districts south of central Osaka.",
      "tip": "This is not central Osaka. Plan transit and crowd logistics carefully.",
      "priority": "high",
      "includeInIcs": true,
      "isOngoing": false,
      "programTbd": false,
      "lastVerified": "2026-07-07"
    },
    {
      "id": "kyoto-music-expo-2026",
      "title": "Kyoto Music Expo 2026",
      "dateStart": "2026-10-10",
      "dateEnd": "2026-10-11",
      "city": "Kyoto",
      "area": "Umekoji",
      "venue": "Umekoji Park Lawn Plaza",
      "time": "Gate 10:00; start 11:30",
      "category": "Music Festival",
      "tags": [
        "music",
        "outdoor",
        "Kyoto",
        "Quruli"
      ],
      "lgbtq": false,
      "cost": "Ticket required",
      "status": "Confirmed by current source",
      "sourceName": "Kyoto City Official Travel Guide",
      "sourceUrl": "https://ja.kyoto.travel/event/single.php?event_id=5272",
      "description": "Outdoor music festival in Umekoji Park with Quruli and a multi-artist lineup.",
      "tip": "A strong Kyoto day-trip option, but it overlaps Rainbow Festa and MINAMI WHEEL.",
      "priority": "high",
      "includeInIcs": true,
      "isOngoing": false,
      "programTbd": false,
      "lastVerified": "2026-07-07"
    },
    {
      "id": "usj-discover-u-25th",
      "title": "Universal Studios Japan 25th Anniversary: Discover U!!!",
      "dateStart": "2026-10-09",
      "dateEnd": "2026-10-21",
      "city": "Osaka",
      "area": "Bay Area",
      "venue": "Universal Studios Japan",
      "time": "Park hours vary by date",
      "category": "Pop Culture / Theme Park",
      "tags": [
        "USJ",
        "anniversary",
        "parade",
        "shows",
        "theme park"
      ],
      "lgbtq": false,
      "cost": "Park ticket required",
      "status": "Confirmed by current source",
      "sourceName": "Universal Studios Japan official",
      "sourceUrl": "https://www.usj.co.jp/web/en/us/25th-anniversary-discover-u",
      "description": "Official 25th-anniversary programme running during the trip, including special entertainment and anniversary experiences.",
      "tip": "I did not add USJ Halloween as a dated event because I did not find an official 2026 Halloween date announcement.",
      "priority": "normal",
      "includeInIcs": true,
      "isOngoing": true,
      "programTbd": false,
      "lastVerified": "2026-07-07"
    },
    {
      "id": "parco-american-dream",
      "title": "PARCO Produce 2026: American Dream",
      "dateStart": "2026-10-09",
      "dateEnd": "2026-10-12",
      "city": "Osaka",
      "area": "Morinomiya",
      "venue": "Morinomiya Piloti Hall",
      "time": "Check source",
      "category": "Theater / Performance",
      "tags": [
        "theater",
        "stage"
      ],
      "lgbtq": false,
      "cost": "Ticket required",
      "status": "Confirmed by current source",
      "sourceName": "Kyodo Osaka",
      "sourceUrl": "https://kyodo-osaka.co.jp/calendar/202610",
      "description": "Stage production listed on Kyodo Osaka for Oct 8-12.",
      "tip": "",
      "priority": "normal",
      "includeInIcs": true,
      "isOngoing": false,
      "programTbd": false,
      "lastVerified": "2026-07-07"
    },
    {
      "id": "takashima-chisako-zawatsuku",
      "title": "Takashima Chisako: Zawatsuku! Ongakukai 2026",
      "dateStart": "2026-10-09",
      "dateEnd": "2026-10-09",
      "city": "Osaka",
      "area": "Osaka Castle Park",
      "venue": "Osaka Castle Hall",
      "time": "Check source",
      "category": "Concert",
      "tags": [
        "classical crossover",
        "concert"
      ],
      "lgbtq": false,
      "cost": "Ticket required",
      "status": "Confirmed by current source",
      "sourceName": "Kyodo Osaka",
      "sourceUrl": "https://kyodo-osaka.co.jp/calendar/202610",
      "description": "",
      "tip": "",
      "priority": "normal",
      "includeInIcs": true,
      "isOngoing": false,
      "programTbd": false,
      "lastVerified": "2026-07-07"
    },
    {
      "id": "yamashita-tatsuro-kyoto",
      "title": "Tatsuro Yamashita Performance 2026",
      "dateStart": "2026-10-09",
      "dateEnd": "2026-10-09",
      "city": "Kyoto",
      "area": "Okazaki",
      "venue": "ROHM Theatre Kyoto",
      "time": "Check source",
      "category": "Concert",
      "tags": [
        "J-pop",
        "Kyoto"
      ],
      "lgbtq": false,
      "cost": "Ticket required",
      "status": "Confirmed by current source",
      "sourceName": "Kyodo Osaka",
      "sourceUrl": "https://kyodo-osaka.co.jp/calendar/202610",
      "description": "",
      "tip": "",
      "priority": "normal",
      "includeInIcs": true,
      "isOngoing": false,
      "programTbd": false,
      "lastVerified": "2026-07-07"
    },
    {
      "id": "kballet-swan-lake",
      "title": "K-BALLET TOKYO: Swan Lake",
      "dateStart": "2026-10-09",
      "dateEnd": "2026-10-10",
      "city": "Osaka",
      "area": "Nakanoshima",
      "venue": "Festival Hall",
      "time": "Check source",
      "category": "Theater / Dance",
      "tags": [
        "ballet",
        "dance",
        "classical"
      ],
      "lgbtq": false,
      "cost": "Ticket required",
      "status": "Confirmed by current source",
      "sourceName": "Kyodo Osaka",
      "sourceUrl": "https://kyodo-osaka.co.jp/calendar/202610",
      "description": "",
      "tip": "",
      "priority": "normal",
      "includeInIcs": true,
      "isOngoing": false,
      "programTbd": false,
      "lastVerified": "2026-07-07"
    },
    {
      "id": "fujii-fumiya-arena",
      "title": "Fumiya Fujii Arena Live 2026: Future Pixels",
      "dateStart": "2026-10-10",
      "dateEnd": "2026-10-10",
      "city": "Osaka",
      "area": "Osaka Castle Park",
      "venue": "Osaka Castle Hall",
      "time": "Check source",
      "category": "Concert",
      "tags": [
        "J-pop",
        "arena"
      ],
      "lgbtq": false,
      "cost": "Ticket required",
      "status": "Confirmed by current source",
      "sourceName": "Kyodo Osaka",
      "sourceUrl": "https://kyodo-osaka.co.jp/calendar/202610",
      "description": "",
      "tip": "",
      "priority": "normal",
      "includeInIcs": true,
      "isOngoing": false,
      "programTbd": false,
      "lastVerified": "2026-07-07"
    },
    {
      "id": "disney-on-classic-sakai",
      "title": "Disney on Classic: A Magical Night 2026 - Sakai",
      "dateStart": "2026-10-10",
      "dateEnd": "2026-10-10",
      "city": "Osaka",
      "area": "Sakai",
      "venue": "Fenice Sakai",
      "time": "Check source",
      "category": "Concert",
      "tags": [
        "orchestra",
        "Disney",
        "family"
      ],
      "lgbtq": false,
      "cost": "Ticket required",
      "status": "Confirmed by current source",
      "sourceName": "eplus / Kyodo Osaka",
      "sourceUrl": "https://eplus.jp/sf/event/month-10/kansai/osaka",
      "description": "",
      "tip": "",
      "priority": "normal",
      "includeInIcs": true,
      "isOngoing": false,
      "programTbd": false,
      "lastVerified": "2026-07-07"
    },
    {
      "id": "hotei-kyoto",
      "title": "HOTEI: Rock and Soul Tour 2026",
      "dateStart": "2026-10-10",
      "dateEnd": "2026-10-11",
      "city": "Kyoto",
      "area": "Okazaki",
      "venue": "ROHM Theatre Kyoto",
      "time": "Check source",
      "category": "Concert",
      "tags": [
        "rock",
        "Kyoto"
      ],
      "lgbtq": false,
      "cost": "Ticket required",
      "status": "Confirmed by current source",
      "sourceName": "Kyodo Osaka",
      "sourceUrl": "https://kyodo-osaka.co.jp/calendar/202610",
      "description": "",
      "tip": "",
      "priority": "normal",
      "includeInIcs": true,
      "isOngoing": false,
      "programTbd": false,
      "lastVerified": "2026-07-07"
    },
    {
      "id": "zutomayo-nara",
      "title": "ZUTOMAYO: Legacy Zombie Labo - Bunka Denrai",
      "dateStart": "2026-10-10",
      "dateEnd": "2026-10-11",
      "city": "Nara",
      "area": "Heijo Palace Site",
      "venue": "Heijo Palace Site special outdoor venue",
      "time": "Check source",
      "category": "Concert",
      "tags": [
        "J-pop",
        "outdoor",
        "Nara"
      ],
      "lgbtq": false,
      "cost": "Ticket required",
      "status": "Confirmed by current source",
      "sourceName": "Kyodo Osaka",
      "sourceUrl": "https://kyodo-osaka.co.jp/calendar/202610",
      "description": "",
      "tip": "",
      "priority": "normal",
      "includeInIcs": true,
      "isOngoing": false,
      "programTbd": false,
      "lastVerified": "2026-07-07"
    },
    {
      "id": "orange-range-orix",
      "title": "ORANGE RANGE Live Tour 025-026",
      "dateStart": "2026-10-11",
      "dateEnd": "2026-10-11",
      "city": "Osaka",
      "area": "Nishi-ku",
      "venue": "ORIX Theater",
      "time": "Check source",
      "category": "Concert",
      "tags": [
        "rock",
        "J-pop"
      ],
      "lgbtq": false,
      "cost": "Ticket required",
      "status": "Confirmed by current source",
      "sourceName": "Kyodo Osaka",
      "sourceUrl": "https://kyodo-osaka.co.jp/calendar/202610",
      "description": "",
      "tip": "",
      "priority": "normal",
      "includeInIcs": true,
      "isOngoing": false,
      "programTbd": false,
      "lastVerified": "2026-07-07"
    },
    {
      "id": "lorna-shore-namba",
      "title": "LORNA SHORE Japan Tour 2026",
      "dateStart": "2026-10-11",
      "dateEnd": "2026-10-11",
      "city": "Osaka",
      "area": "Namba",
      "venue": "Namba Hatch",
      "time": "Check source",
      "category": "Concert",
      "tags": [
        "metal",
        "international"
      ],
      "lgbtq": false,
      "cost": "Ticket required",
      "status": "Confirmed by current source",
      "sourceName": "Kyodo Osaka",
      "sourceUrl": "https://kyodo-osaka.co.jp/calendar/202610",
      "description": "",
      "tip": "",
      "priority": "normal",
      "includeInIcs": true,
      "isOngoing": false,
      "programTbd": false,
      "lastVerified": "2026-07-07"
    },
    {
      "id": "ishida-gumi-osaka",
      "title": "Ishida-gumi Concert Tour 2026",
      "dateStart": "2026-10-11",
      "dateEnd": "2026-10-11",
      "city": "Osaka",
      "area": "Osaka Castle Park",
      "venue": "Osaka Castle Hall",
      "time": "Check source",
      "category": "Concert",
      "tags": [
        "strings",
        "classical"
      ],
      "lgbtq": false,
      "cost": "Ticket required",
      "status": "Confirmed by current source",
      "sourceName": "Kyodo Osaka",
      "sourceUrl": "https://kyodo-osaka.co.jp/calendar/202610",
      "description": "",
      "tip": "",
      "priority": "normal",
      "includeInIcs": true,
      "isOngoing": false,
      "programTbd": false,
      "lastVerified": "2026-07-07"
    },
    {
      "id": "taro-hakase-festival",
      "title": "Taro Hakase Concert Tour 2026",
      "dateStart": "2026-10-11",
      "dateEnd": "2026-10-12",
      "city": "Osaka",
      "area": "Nakanoshima",
      "venue": "Festival Hall",
      "time": "Check source",
      "category": "Concert",
      "tags": [
        "violin",
        "classical crossover"
      ],
      "lgbtq": false,
      "cost": "Ticket required",
      "status": "Confirmed by current source",
      "sourceName": "Kyodo Osaka",
      "sourceUrl": "https://kyodo-osaka.co.jp/calendar/202610",
      "description": "",
      "tip": "",
      "priority": "normal",
      "includeInIcs": true,
      "isOngoing": false,
      "programTbd": false,
      "lastVerified": "2026-07-07"
    },
    {
      "id": "natori-grand-cube",
      "title": "Natori One-Man Live 2026",
      "dateStart": "2026-10-11",
      "dateEnd": "2026-10-12",
      "city": "Osaka",
      "area": "Nakanoshima",
      "venue": "Grand Cube Osaka",
      "time": "Check source",
      "category": "Concert",
      "tags": [
        "J-pop",
        "internet music"
      ],
      "lgbtq": false,
      "cost": "Ticket required",
      "status": "Confirmed by current source",
      "sourceName": "Kyodo Osaka",
      "sourceUrl": "https://kyodo-osaka.co.jp/calendar/202610",
      "description": "",
      "tip": "",
      "priority": "normal",
      "includeInIcs": true,
      "isOngoing": false,
      "programTbd": false,
      "lastVerified": "2026-07-07"
    },
    {
      "id": "gusokumuzu-minoh",
      "title": "Gusokumuzu One-Man Tour 2026",
      "dateStart": "2026-10-12",
      "dateEnd": "2026-10-12",
      "city": "Osaka",
      "area": "Minoh",
      "venue": "Tokyo Tatemono Brillia Hall Minoh, small hall",
      "time": "Check source",
      "category": "Concert",
      "tags": [
        "band",
        "Minoh"
      ],
      "lgbtq": false,
      "cost": "Ticket required",
      "status": "Confirmed by current source",
      "sourceName": "Kyodo Osaka",
      "sourceUrl": "https://kyodo-osaka.co.jp/calendar/202610",
      "description": "",
      "tip": "",
      "priority": "normal",
      "includeInIcs": true,
      "isOngoing": false,
      "programTbd": false,
      "lastVerified": "2026-07-07"
    },
    {
      "id": "osaka-shion-kyoto",
      "title": "Osaka Shion Wind Orchestra - Dragon Quest Concert",
      "dateStart": "2026-10-12",
      "dateEnd": "2026-10-12",
      "city": "Kyoto",
      "area": "Kitayama",
      "venue": "Kyoto Concert Hall",
      "time": "Check source",
      "category": "Concert",
      "tags": [
        "orchestra",
        "game music",
        "Kyoto"
      ],
      "lgbtq": false,
      "cost": "Ticket required",
      "status": "Confirmed by current source",
      "sourceName": "Kyodo Osaka",
      "sourceUrl": "https://kyodo-osaka.co.jp/calendar/202610",
      "description": "",
      "tip": "",
      "priority": "normal",
      "includeInIcs": true,
      "isOngoing": false,
      "programTbd": false,
      "lastVerified": "2026-07-07"
    },
    {
      "id": "otoda-masanori-namba",
      "title": "Masanori Otoda 30th Anniversary Tour",
      "dateStart": "2026-10-12",
      "dateEnd": "2026-10-12",
      "city": "Osaka",
      "area": "Namba",
      "venue": "Namba Hatch",
      "time": "Check source",
      "category": "Concert",
      "tags": [
        "singer-songwriter"
      ],
      "lgbtq": false,
      "cost": "Ticket required",
      "status": "Confirmed by current source",
      "sourceName": "Kyodo Osaka",
      "sourceUrl": "https://kyodo-osaka.co.jp/calendar/202610",
      "description": "",
      "tip": "",
      "priority": "normal",
      "includeInIcs": true,
      "isOngoing": false,
      "programTbd": false,
      "lastVerified": "2026-07-07"
    },
    {
      "id": "cheeriemans-orix",
      "title": "Cheeriemans Solo Performance",
      "dateStart": "2026-10-12",
      "dateEnd": "2026-10-12",
      "city": "Osaka",
      "area": "Nishi-ku",
      "venue": "ORIX Theater",
      "time": "Check source",
      "category": "Concert",
      "tags": [
        "performance",
        "music"
      ],
      "lgbtq": false,
      "cost": "Ticket required",
      "status": "Confirmed by current source",
      "sourceName": "Kyodo Osaka",
      "sourceUrl": "https://kyodo-osaka.co.jp/calendar/202610",
      "description": "",
      "tip": "",
      "priority": "normal",
      "includeInIcs": true,
      "isOngoing": false,
      "programTbd": false,
      "lastVerified": "2026-07-07"
    },
    {
      "id": "disney-on-classic-kyoto",
      "title": "Disney on Classic: A Magical Night 2026 - Kyoto",
      "dateStart": "2026-10-12",
      "dateEnd": "2026-10-12",
      "city": "Kyoto",
      "area": "Okazaki",
      "venue": "ROHM Theatre Kyoto",
      "time": "Check source",
      "category": "Concert",
      "tags": [
        "orchestra",
        "Disney",
        "family",
        "Kyoto"
      ],
      "lgbtq": false,
      "cost": "Ticket required",
      "status": "Confirmed by current source",
      "sourceName": "Kyodo Osaka",
      "sourceUrl": "https://kyodo-osaka.co.jp/calendar/202610",
      "description": "",
      "tip": "",
      "priority": "normal",
      "includeInIcs": true,
      "isOngoing": false,
      "programTbd": false,
      "lastVerified": "2026-07-07"
    },
    {
      "id": "nelke-bigcat",
      "title": "NELKE TOUR 2026",
      "dateStart": "2026-10-14",
      "dateEnd": "2026-10-14",
      "city": "Osaka",
      "area": "Shinsaibashi",
      "venue": "BIGCAT",
      "time": "Check source",
      "category": "Concert",
      "tags": [
        "live house",
        "Shinsaibashi"
      ],
      "lgbtq": false,
      "cost": "Ticket required",
      "status": "Confirmed by current source",
      "sourceName": "Kyodo Osaka",
      "sourceUrl": "https://kyodo-osaka.co.jp/calendar/202610",
      "description": "",
      "tip": "",
      "priority": "normal",
      "includeInIcs": true,
      "isOngoing": false,
      "programTbd": false,
      "lastVerified": "2026-07-07"
    },
    {
      "id": "mrchildren-osaka-castle",
      "title": "Mr.Children Tour 2026",
      "dateStart": "2026-10-14",
      "dateEnd": "2026-10-15",
      "city": "Osaka",
      "area": "Osaka Castle Park",
      "venue": "Osaka Castle Hall",
      "time": "Check source",
      "category": "Concert",
      "tags": [
        "J-pop",
        "arena"
      ],
      "lgbtq": false,
      "cost": "Ticket required",
      "status": "Confirmed by current source",
      "sourceName": "Kyodo Osaka",
      "sourceUrl": "https://kyodo-osaka.co.jp/calendar/202610",
      "description": "",
      "tip": "",
      "priority": "high",
      "includeInIcs": true,
      "isOngoing": false,
      "programTbd": false,
      "lastVerified": "2026-07-07"
    },
    {
      "id": "yanagisawa-shingo-stage",
      "title": "Shingo Yanagisawa Festival Stage 2026",
      "dateStart": "2026-10-16",
      "dateEnd": "2026-10-17",
      "city": "Osaka",
      "area": "Umeda",
      "venue": "Theater Drama City",
      "time": "Check source",
      "category": "Theater / Performance",
      "tags": [
        "stage",
        "comedy"
      ],
      "lgbtq": false,
      "cost": "Ticket required",
      "status": "Confirmed by current source",
      "sourceName": "Kyodo Osaka",
      "sourceUrl": "https://kyodo-osaka.co.jp/calendar/202610",
      "description": "",
      "tip": "",
      "priority": "normal",
      "includeInIcs": true,
      "isOngoing": false,
      "programTbd": false,
      "lastVerified": "2026-07-07"
    },
    {
      "id": "cloudy-shangrila",
      "title": "Cloudy Tour 2026",
      "dateStart": "2026-10-17",
      "dateEnd": "2026-10-17",
      "city": "Osaka",
      "area": "Umeda",
      "venue": "Umeda Shangri-La",
      "time": "Check source",
      "category": "Concert",
      "tags": [
        "live house"
      ],
      "lgbtq": false,
      "cost": "Ticket required",
      "status": "Confirmed by current source",
      "sourceName": "Kyodo Osaka",
      "sourceUrl": "https://kyodo-osaka.co.jp/calendar/202610",
      "description": "",
      "tip": "",
      "priority": "normal",
      "includeInIcs": true,
      "isOngoing": false,
      "programTbd": false,
      "lastVerified": "2026-07-07"
    },
    {
      "id": "suri-gorilla",
      "title": "Suri Tour 2026",
      "dateStart": "2026-10-17",
      "dateEnd": "2026-10-17",
      "city": "Osaka",
      "area": "Suminoe",
      "venue": "GORILLA HALL OSAKA",
      "time": "Check source",
      "category": "Concert",
      "tags": [
        "live house"
      ],
      "lgbtq": false,
      "cost": "Ticket required",
      "status": "Confirmed by current source",
      "sourceName": "Kyodo Osaka",
      "sourceUrl": "https://kyodo-osaka.co.jp/calendar/202610",
      "description": "",
      "tip": "",
      "priority": "normal",
      "includeInIcs": true,
      "isOngoing": false,
      "programTbd": false,
      "lastVerified": "2026-07-07"
    },
    {
      "id": "masayoshi-takanaka-osaka",
      "title": "Masayoshi Takanaka 2026 Live",
      "dateStart": "2026-10-17",
      "dateEnd": "2026-10-17",
      "city": "Osaka",
      "area": "Osaka Castle Park",
      "venue": "Osaka Castle Outdoor Music Hall",
      "time": "Check source",
      "category": "Concert",
      "tags": [
        "guitar",
        "outdoor"
      ],
      "lgbtq": false,
      "cost": "Ticket required",
      "status": "Confirmed by current source",
      "sourceName": "Kyodo Osaka",
      "sourceUrl": "https://kyodo-osaka.co.jp/calendar/202610",
      "description": "",
      "tip": "",
      "priority": "normal",
      "includeInIcs": true,
      "isOngoing": false,
      "programTbd": false,
      "lastVerified": "2026-07-07"
    },
    {
      "id": "moriyama-ryoko-festival",
      "title": "Ryoko Moriyama Concert 2026",
      "dateStart": "2026-10-18",
      "dateEnd": "2026-10-18",
      "city": "Osaka",
      "area": "Nakanoshima",
      "venue": "Festival Hall",
      "time": "Check source",
      "category": "Concert",
      "tags": [
        "vocal",
        "classic pop"
      ],
      "lgbtq": false,
      "cost": "Ticket required",
      "status": "Confirmed by current source",
      "sourceName": "Kyodo Osaka",
      "sourceUrl": "https://kyodo-osaka.co.jp/calendar/202610",
      "description": "",
      "tip": "",
      "priority": "normal",
      "includeInIcs": true,
      "isOngoing": false,
      "programTbd": false,
      "lastVerified": "2026-07-07"
    },
    {
      "id": "suspended4th-shangrila",
      "title": "Suspended 4th Live 2026",
      "dateStart": "2026-10-18",
      "dateEnd": "2026-10-18",
      "city": "Osaka",
      "area": "Umeda",
      "venue": "Umeda Shangri-La",
      "time": "Check source",
      "category": "Concert",
      "tags": [
        "rock",
        "live house"
      ],
      "lgbtq": false,
      "cost": "Ticket required",
      "status": "Confirmed by current source",
      "sourceName": "Kyodo Osaka",
      "sourceUrl": "https://kyodo-osaka.co.jp/calendar/202610",
      "description": "",
      "tip": "",
      "priority": "normal",
      "includeInIcs": true,
      "isOngoing": false,
      "programTbd": false,
      "lastVerified": "2026-07-07"
    },
    {
      "id": "koji-tamaki-kyoto",
      "title": "Koji Tamaki Concert 2026",
      "dateStart": "2026-10-19",
      "dateEnd": "2026-10-19",
      "city": "Kyoto",
      "area": "Okazaki",
      "venue": "ROHM Theatre Kyoto",
      "time": "Check source",
      "category": "Concert",
      "tags": [
        "vocal",
        "Kyoto"
      ],
      "lgbtq": false,
      "cost": "Ticket required",
      "status": "Confirmed by current source",
      "sourceName": "Kyodo Osaka",
      "sourceUrl": "https://kyodo-osaka.co.jp/calendar/202610",
      "description": "",
      "tip": "",
      "priority": "normal",
      "includeInIcs": true,
      "isOngoing": false,
      "programTbd": false,
      "lastVerified": "2026-07-07"
    },
    {
      "id": "hayashibe-satoshi-festival",
      "title": "Satoshi Hayashibe Concert 2026",
      "dateStart": "2026-10-20",
      "dateEnd": "2026-10-20",
      "city": "Osaka",
      "area": "Nakanoshima",
      "venue": "Festival Hall",
      "time": "Check source",
      "category": "Concert",
      "tags": [
        "vocal",
        "concert"
      ],
      "lgbtq": false,
      "cost": "Ticket required",
      "status": "Confirmed by current source",
      "sourceName": "Kyodo Osaka",
      "sourceUrl": "https://kyodo-osaka.co.jp/calendar/202610",
      "description": "",
      "tip": "",
      "priority": "normal",
      "includeInIcs": true,
      "isOngoing": false,
      "programTbd": false,
      "lastVerified": "2026-07-07"
    },
    {
      "id": "billboard-kei-aran",
      "title": "Billboard Live Osaka: Kei Aran 35th Live with Kazutaka Ishii",
      "dateStart": "2026-10-09",
      "dateEnd": "2026-10-09",
      "city": "Osaka",
      "area": "Umeda",
      "venue": "Billboard Live Osaka, HERBIS PLAZA ENT",
      "time": "1st stage 16:00; 2nd stage 19:00",
      "category": "Club / Jazz / Live",
      "tags": [
        "Billboard Live",
        "cabaret",
        "Umeda"
      ],
      "lgbtq": false,
      "cost": "Ticket required",
      "status": "Confirmed by current source",
      "sourceName": "Billboard Live Osaka",
      "sourceUrl": "https://www.billboard-live.com/osaka/schedules?month=2026-10-01",
      "description": "",
      "tip": "",
      "priority": "normal",
      "includeInIcs": true,
      "isOngoing": false,
      "programTbd": false,
      "lastVerified": "2026-07-07"
    },
    {
      "id": "billboard-nick-heyward",
      "title": "Billboard Live Osaka: Nick Heyward",
      "dateStart": "2026-10-12",
      "dateEnd": "2026-10-12",
      "city": "Osaka",
      "area": "Umeda",
      "venue": "Billboard Live Osaka, HERBIS PLAZA ENT",
      "time": "1st stage 16:00; 2nd stage 19:00",
      "category": "Club / Jazz / Live",
      "tags": [
        "Billboard Live",
        "international",
        "pop"
      ],
      "lgbtq": false,
      "cost": "Ticket required",
      "status": "Confirmed by current source",
      "sourceName": "Billboard Live Osaka",
      "sourceUrl": "https://www.billboard-live.com/osaka/schedules?month=2026-10-01",
      "description": "",
      "tip": "",
      "priority": "normal",
      "includeInIcs": true,
      "isOngoing": false,
      "programTbd": false,
      "lastVerified": "2026-07-07"
    },
    {
      "id": "billboard-woong-san",
      "title": "Billboard Live Osaka: Woong San 30th Anniversary Japan Tour",
      "dateStart": "2026-10-13",
      "dateEnd": "2026-10-13",
      "city": "Osaka",
      "area": "Umeda",
      "venue": "Billboard Live Osaka, HERBIS PLAZA ENT",
      "time": "1st stage 17:30; 2nd stage 20:30",
      "category": "Club / Jazz / Live",
      "tags": [
        "Billboard Live",
        "jazz",
        "vocals"
      ],
      "lgbtq": false,
      "cost": "Ticket required",
      "status": "Confirmed by current source",
      "sourceName": "Billboard Live Osaka",
      "sourceUrl": "https://www.billboard-live.com/osaka/schedules?month=2026-10-01",
      "description": "",
      "tip": "",
      "priority": "normal",
      "includeInIcs": true,
      "isOngoing": false,
      "programTbd": false,
      "lastVerified": "2026-07-07"
    },
    {
      "id": "billboard-zard-acoustic",
      "title": "Billboard Live Osaka: ZARD Acoustic Live 2026",
      "dateStart": "2026-10-15",
      "dateEnd": "2026-10-16",
      "city": "Osaka",
      "area": "Umeda",
      "venue": "Billboard Live Osaka, HERBIS PLAZA ENT",
      "time": "1st stage 17:30; 2nd stage 20:30",
      "category": "Club / Jazz / Live",
      "tags": [
        "Billboard Live",
        "acoustic",
        "J-pop"
      ],
      "lgbtq": false,
      "cost": "Ticket required",
      "status": "Confirmed by current source",
      "sourceName": "Billboard Live Osaka",
      "sourceUrl": "https://www.billboard-live.com/osaka/schedules?month=2026-10-01",
      "description": "",
      "tip": "",
      "priority": "normal",
      "includeInIcs": true,
      "isOngoing": false,
      "programTbd": false,
      "lastVerified": "2026-07-07"
    },
    {
      "id": "billboard-lego-big-morl",
      "title": "Billboard Live Osaka: LEGO BIG MORL 20th Anniversary Acoustic",
      "dateStart": "2026-10-18",
      "dateEnd": "2026-10-18",
      "city": "Osaka",
      "area": "Umeda",
      "venue": "Billboard Live Osaka, HERBIS PLAZA ENT",
      "time": "1st stage 15:00; 2nd stage 18:00",
      "category": "Club / Jazz / Live",
      "tags": [
        "Billboard Live",
        "acoustic",
        "band"
      ],
      "lgbtq": false,
      "cost": "Ticket required",
      "status": "Confirmed by current source",
      "sourceName": "Billboard Live Osaka",
      "sourceUrl": "https://www.billboard-live.com/osaka/schedules?month=2026-10-01",
      "description": "",
      "tip": "",
      "priority": "normal",
      "includeInIcs": true,
      "isOngoing": false,
      "programTbd": false,
      "lastVerified": "2026-07-07"
    },
    {
      "id": "big-extinction-exhibition",
      "title": "Special Exhibition: The Big Five Mass Extinctions",
      "dateStart": "2026-10-09",
      "dateEnd": "2026-10-12",
      "city": "Osaka",
      "area": "Nagai",
      "venue": "Osaka Museum of Natural History",
      "time": "Museum hours; final days during trip",
      "category": "Exhibition / Museum",
      "tags": [
        "museum",
        "science",
        "natural history"
      ],
      "lgbtq": false,
      "cost": "Ticket required",
      "status": "Confirmed by current source",
      "sourceName": "eplus / Walkerplus",
      "sourceUrl": "https://eplus.jp/sf/event/month-10/kansai/osaka",
      "description": "Special exhibition tracing life evolution through the five major mass extinctions.",
      "tip": "",
      "priority": "normal",
      "includeInIcs": true,
      "isOngoing": false,
      "programTbd": false,
      "lastVerified": "2026-07-07"
    },
    {
      "id": "real-escape-lab-ebisucho",
      "title": "Real Escape Game: Escape from a Certain Laboratory",
      "dateStart": "2026-10-09",
      "dateEnd": "2026-10-21",
      "city": "Osaka",
      "area": "Ebisu-cho / Shinsekai",
      "venue": "Real Escape Game Osaka Ebisu-cho",
      "time": "Check source",
      "category": "Interactive / Mystery",
      "tags": [
        "escape room",
        "puzzle",
        "activity"
      ],
      "lgbtq": false,
      "cost": "Ticket required",
      "status": "Confirmed by current source",
      "sourceName": "Walkerplus",
      "sourceUrl": "https://www.walkerplus.com/event_list/10/ar0727/",
      "description": "Long-running Real Escape Game revival listed through Oct 25.",
      "tip": "",
      "priority": "normal",
      "includeInIcs": true,
      "isOngoing": true,
      "programTbd": false,
      "lastVerified": "2026-07-07"
    },
    {
      "id": "conan-real-escape-shinsaibashi",
      "title": "Detective Conan Real Escape Game: Escape from the Highway Chase",
      "dateStart": "2026-10-09",
      "dateEnd": "2026-10-12",
      "city": "Osaka",
      "area": "Shinsaibashi",
      "venue": "Real Escape Game Osaka Shinsaibashi",
      "time": "Check source",
      "category": "Interactive / Mystery",
      "tags": [
        "anime",
        "escape room",
        "Conan"
      ],
      "lgbtq": false,
      "cost": "Ticket required",
      "status": "Confirmed by current source",
      "sourceName": "Walkerplus",
      "sourceUrl": "https://www.walkerplus.com/event_list/10/ar0727/",
      "description": "",
      "tip": "",
      "priority": "normal",
      "includeInIcs": true,
      "isOngoing": false,
      "programTbd": false,
      "lastVerified": "2026-07-07"
    },
    {
      "id": "night-magic-school-hirakata-1011",
      "title": "Night Escape from the Magic School - Hirakata Park",
      "dateStart": "2026-10-11",
      "dateEnd": "2026-10-11",
      "city": "Osaka",
      "area": "Hirakata",
      "venue": "Hirakata Park",
      "time": "18:30 start",
      "category": "Interactive / Mystery",
      "tags": [
        "night event",
        "escape game",
        "theme park"
      ],
      "lgbtq": false,
      "cost": "Ticket required",
      "status": "Confirmed by current source",
      "sourceName": "eplus",
      "sourceUrl": "https://eplus.jp/sf/event/month-10/kansai/osaka",
      "description": "",
      "tip": "",
      "priority": "normal",
      "includeInIcs": true,
      "isOngoing": false,
      "programTbd": false,
      "lastVerified": "2026-07-07"
    },
    {
      "id": "night-magic-school-hirakata-1012",
      "title": "Night Escape from the Magic School - Hirakata Park",
      "dateStart": "2026-10-12",
      "dateEnd": "2026-10-12",
      "city": "Osaka",
      "area": "Hirakata",
      "venue": "Hirakata Park",
      "time": "18:30 start",
      "category": "Interactive / Mystery",
      "tags": [
        "night event",
        "escape game",
        "theme park"
      ],
      "lgbtq": false,
      "cost": "Ticket required",
      "status": "Confirmed by current source",
      "sourceName": "eplus",
      "sourceUrl": "https://eplus.jp/sf/event/month-10/kansai/osaka",
      "description": "",
      "tip": "",
      "priority": "normal",
      "includeInIcs": true,
      "isOngoing": false,
      "programTbd": false,
      "lastVerified": "2026-07-07"
    },
    {
      "id": "night-magic-school-hirakata-1017",
      "title": "Night Escape from the Magic School - Hirakata Park",
      "dateStart": "2026-10-17",
      "dateEnd": "2026-10-17",
      "city": "Osaka",
      "area": "Hirakata",
      "venue": "Hirakata Park",
      "time": "18:30 start",
      "category": "Interactive / Mystery",
      "tags": [
        "night event",
        "escape game",
        "theme park"
      ],
      "lgbtq": false,
      "cost": "Ticket required",
      "status": "Confirmed by current source",
      "sourceName": "eplus",
      "sourceUrl": "https://eplus.jp/sf/event/month-10/kansai/osaka",
      "description": "",
      "tip": "",
      "priority": "normal",
      "includeInIcs": true,
      "isOngoing": false,
      "programTbd": false,
      "lastVerified": "2026-07-07"
    },
    {
      "id": "night-magic-school-hirakata-1018",
      "title": "Night Escape from the Magic School - Hirakata Park",
      "dateStart": "2026-10-18",
      "dateEnd": "2026-10-18",
      "city": "Osaka",
      "area": "Hirakata",
      "venue": "Hirakata Park",
      "time": "18:30 start",
      "category": "Interactive / Mystery",
      "tags": [
        "night event",
        "escape game",
        "theme park"
      ],
      "lgbtq": false,
      "cost": "Ticket required",
      "status": "Confirmed by current source",
      "sourceName": "eplus",
      "sourceUrl": "https://eplus.jp/sf/event/month-10/kansai/osaka",
      "description": "",
      "tip": "",
      "priority": "normal",
      "includeInIcs": true,
      "isOngoing": false,
      "programTbd": false,
      "lastVerified": "2026-07-07"
    },
    {
      "id": "osaka-station-city-mystery",
      "title": "Osaka Station City 15th Anniversary Mystery Game",
      "dateStart": "2026-10-09",
      "dateEnd": "2026-10-21",
      "city": "Osaka",
      "area": "Umeda",
      "venue": "Osaka Station City",
      "time": "Check source",
      "category": "Interactive / Mystery",
      "tags": [
        "self-guided",
        "puzzle",
        "Umeda"
      ],
      "lgbtq": false,
      "cost": "Check source",
      "status": "Confirmed by current source",
      "sourceName": "eplus",
      "sourceUrl": "https://eplus.jp/sf/event/month-10/kansai/osaka",
      "description": "Self-guided mystery game listed by eplus through Nov 30.",
      "tip": "",
      "priority": "normal",
      "includeInIcs": true,
      "isOngoing": true,
      "programTbd": false,
      "lastVerified": "2026-07-07"
    },
    {
      "id": "fantane-namikiri",
      "title": "Okaasan to Issho: Fantane! to Asobo PLUS",
      "dateStart": "2026-10-12",
      "dateEnd": "2026-10-12",
      "city": "Osaka",
      "area": "Kishiwada",
      "venue": "Nankai Namikiri Hall",
      "time": "13:00 and 15:30",
      "category": "Family / Pop Culture",
      "tags": [
        "family",
        "children",
        "show"
      ],
      "lgbtq": false,
      "cost": "Ticket required",
      "status": "Confirmed by current source",
      "sourceName": "eplus",
      "sourceUrl": "https://eplus.jp/sf/event/month-10/kansai/osaka",
      "description": "",
      "tip": "",
      "priority": "normal",
      "includeInIcs": true,
      "isOngoing": false,
      "programTbd": false,
      "lastVerified": "2026-07-07"
    },
    {
      "id": "denjiro-science-toyonaka",
      "title": "Denjiro Science Show - Toyonaka",
      "dateStart": "2026-10-11",
      "dateEnd": "2026-10-11",
      "city": "Osaka",
      "area": "Toyonaka",
      "venue": "Toyonaka Performing Arts Center",
      "time": "12:00 and 14:30",
      "category": "Family / Pop Culture",
      "tags": [
        "science",
        "family"
      ],
      "lgbtq": false,
      "cost": "Ticket required",
      "status": "Confirmed by current source",
      "sourceName": "eplus",
      "sourceUrl": "https://eplus.jp/sf/event/month-10/kansai/osaka",
      "description": "",
      "tip": "",
      "priority": "normal",
      "includeInIcs": true,
      "isOngoing": false,
      "programTbd": false,
      "lastVerified": "2026-07-07"
    },
    {
      "id": "denjiro-science-yao",
      "title": "Denjiro Science Show - Yao",
      "dateStart": "2026-10-12",
      "dateEnd": "2026-10-12",
      "city": "Osaka",
      "area": "Yao",
      "venue": "Yao City Cultural Hall Prism Hall",
      "time": "12:30 and 15:30",
      "category": "Family / Pop Culture",
      "tags": [
        "science",
        "family"
      ],
      "lgbtq": false,
      "cost": "Ticket required",
      "status": "Confirmed by current source",
      "sourceName": "eplus",
      "sourceUrl": "https://eplus.jp/sf/event/month-10/kansai/osaka",
      "description": "",
      "tip": "",
      "priority": "normal",
      "includeInIcs": true,
      "isOngoing": false,
      "programTbd": false,
      "lastVerified": "2026-07-07"
    },
    {
      "id": "harukas-sorameshi-bbq",
      "title": "Harukas Sora-meshi Rooftop BBQ",
      "dateStart": "2026-10-09",
      "dateEnd": "2026-10-18",
      "city": "Osaka",
      "area": "Tennoji / Abeno",
      "venue": "Harukas 300",
      "time": "Check source",
      "category": "Food / Seasonal",
      "tags": [
        "rooftop",
        "BBQ",
        "night view"
      ],
      "lgbtq": false,
      "cost": "Reservation / fee likely required",
      "status": "Confirmed by current source",
      "sourceName": "Walkerplus",
      "sourceUrl": "https://www.walkerplus.com/event_list/10/ar0727/",
      "description": "",
      "tip": "",
      "priority": "normal",
      "includeInIcs": true,
      "isOngoing": true,
      "programTbd": false,
      "lastVerified": "2026-07-07"
    },
    {
      "id": "hankyu-umeda-beer-garden",
      "title": "Hankyu Umeda Rooftop Beer Garden: Traveling Rooftop Beer Garden",
      "dateStart": "2026-10-09",
      "dateEnd": "2026-10-12",
      "city": "Osaka",
      "area": "Umeda",
      "venue": "Hankyu Umeda Main Store",
      "time": "Check source",
      "category": "Food / Seasonal",
      "tags": [
        "beer garden",
        "rooftop",
        "Umeda"
      ],
      "lgbtq": false,
      "cost": "Reservation / fee likely required",
      "status": "Confirmed by current source",
      "sourceName": "Walkerplus",
      "sourceUrl": "https://www.walkerplus.com/event_list/10/ar0727/",
      "description": "",
      "tip": "",
      "priority": "normal",
      "includeInIcs": true,
      "isOngoing": true,
      "programTbd": false,
      "lastVerified": "2026-07-07"
    },
    {
      "id": "tenmabashi-yatai-bbq",
      "title": "Temmabashi Rooftop Festival Stall and BBQ Beer Garden",
      "dateStart": "2026-10-09",
      "dateEnd": "2026-10-18",
      "city": "Osaka",
      "area": "Temmabashi",
      "venue": "Keihan City Mall",
      "time": "Check source",
      "category": "Food / Seasonal",
      "tags": [
        "beer garden",
        "festival stalls",
        "rooftop"
      ],
      "lgbtq": false,
      "cost": "Reservation / fee likely required",
      "status": "Confirmed by current source",
      "sourceName": "Walkerplus",
      "sourceUrl": "https://www.walkerplus.com/event_list/10/ar0727/",
      "description": "",
      "tip": "",
      "priority": "normal",
      "includeInIcs": true,
      "isOngoing": true,
      "programTbd": false,
      "lastVerified": "2026-07-07"
    },
    {
      "id": "umeda-rooftop-beer-garden",
      "title": "Umeda Great Hall Rooftop BBQ Beer Garden",
      "dateStart": "2026-10-09",
      "dateEnd": "2026-10-21",
      "city": "Osaka",
      "area": "Umeda",
      "venue": "Ohatsu Tenjin shopping street area",
      "time": "Check source",
      "category": "Food / Seasonal",
      "tags": [
        "beer garden",
        "rooftop",
        "Umeda"
      ],
      "lgbtq": false,
      "cost": "Reservation / fee likely required",
      "status": "Confirmed by current source",
      "sourceName": "Walkerplus",
      "sourceUrl": "https://www.walkerplus.com/event_list/10/ar0727/",
      "description": "",
      "tip": "",
      "priority": "normal",
      "includeInIcs": true,
      "isOngoing": true,
      "programTbd": false,
      "lastVerified": "2026-07-07"
    },
    {
      "id": "dotonbori-water-walk",
      "title": "Dotonbori Guided Water Walk by Parasol Boat",
      "dateStart": "2026-10-09",
      "dateEnd": "2026-10-21",
      "city": "Osaka",
      "area": "Dotonbori / Higashi-Yokobori",
      "venue": "Nihon City SUP Association",
      "time": "Check source",
      "category": "Experience / Tour",
      "tags": [
        "water",
        "tour",
        "Dotonbori"
      ],
      "lgbtq": false,
      "cost": "Reservation / fee required",
      "status": "Confirmed by current source",
      "sourceName": "Walkerplus",
      "sourceUrl": "https://www.walkerplus.com/event_list/10/ar0727/",
      "description": "",
      "tip": "",
      "priority": "normal",
      "includeInIcs": true,
      "isOngoing": true,
      "programTbd": false,
      "lastVerified": "2026-07-07"
    },
    {
      "id": "daianji-kannon-special-opening",
      "title": "Daian-ji: Hidden Eleven-faced Kannon Special Opening",
      "dateStart": "2026-10-09",
      "dateEnd": "2026-10-21",
      "city": "Nara",
      "area": "Daianji",
      "venue": "Daian-ji Temple",
      "time": "Check source",
      "category": "Temple / Shrine",
      "tags": [
        "temple",
        "special opening",
        "Buddhist art"
      ],
      "lgbtq": false,
      "cost": "Temple fee/donation may apply",
      "status": "Confirmed by current source",
      "sourceName": "Nara City Tourism",
      "sourceUrl": "https://narashikanko.or.jp/event/detail_10351.html",
      "description": "Autumn special opening listed for Oct 1-Nov 30.",
      "tip": "",
      "priority": "normal",
      "includeInIcs": true,
      "isOngoing": true,
      "programTbd": false,
      "lastVerified": "2026-07-07"
    },
    {
      "id": "nara-musikfest-platform",
      "title": "Nara for Culture / Musikfest Nara 2026",
      "dateStart": "2026-10-09",
      "dateEnd": "2026-10-21",
      "city": "Nara",
      "area": "Prefecture-wide",
      "venue": "Various venues",
      "time": "Programme varies by date",
      "category": "Music Festival",
      "tags": [
        "music",
        "Nara",
        "culture"
      ],
      "lgbtq": false,
      "cost": "Varies",
      "status": "Festival period confirmed; check programme for exact daily events",
      "sourceName": "Nara City Tourism",
      "sourceUrl": "https://narashikanko.or.jp/event/detail_10294.html",
      "description": "Official Nara music/culture programme running May 1-Dec 31.",
      "tip": "",
      "priority": "normal",
      "includeInIcs": true,
      "isOngoing": true,
      "programTbd": true,
      "lastVerified": "2026-07-07"
    },
    {
      "id": "daimokutate-yahashira",
      "title": "Daimokutate at Yahashira Shrine",
      "dateStart": "2026-10-12",
      "dateEnd": "2026-10-12",
      "city": "Nara",
      "area": "Kamitakawa-cho",
      "venue": "Yahashira Shrine",
      "time": "Check source",
      "category": "Traditional Festival",
      "tags": [
        "folk performing art",
        "UNESCO",
        "traditional"
      ],
      "lgbtq": false,
      "cost": "Free public viewing/check source",
      "status": "Confirmed by current source",
      "sourceName": "Nara City Tourism",
      "sourceUrl": "https://narashikanko.or.jp/event/detail_10206.html",
      "description": "",
      "tip": "",
      "priority": "normal",
      "includeInIcs": true,
      "isOngoing": false,
      "programTbd": false,
      "lastVerified": "2026-07-07"
    },
    {
      "id": "goryo-autumn-grand-festival",
      "title": "Goryo Shrine Autumn Grand Festival / Togyoshiki",
      "dateStart": "2026-10-13",
      "dateEnd": "2026-10-13",
      "city": "Nara",
      "area": "Naramachi",
      "venue": "Goryo Shrine",
      "time": "Check source",
      "category": "Traditional Festival",
      "tags": [
        "shrine",
        "procession",
        "traditional"
      ],
      "lgbtq": false,
      "cost": "Free public viewing/check source",
      "status": "Confirmed by current source",
      "sourceName": "Nara City Tourism",
      "sourceUrl": "https://narashikanko.or.jp/event/detail_10344.html",
      "description": "",
      "tip": "",
      "priority": "normal",
      "includeInIcs": true,
      "isOngoing": false,
      "programTbd": false,
      "lastVerified": "2026-07-07"
    },
    {
      "id": "todaiji-great-buddha-autumn",
      "title": "Todai-ji Great Buddha Autumn Festival",
      "dateStart": "2026-10-15",
      "dateEnd": "2026-10-15",
      "city": "Nara",
      "area": "Nara Park",
      "venue": "Todai-ji Temple",
      "time": "10:00 ceremony listed by Nara City Tourism",
      "category": "Temple / Shrine",
      "tags": [
        "temple",
        "ceremony",
        "Great Buddha"
      ],
      "lgbtq": false,
      "cost": "Temple admission/check source",
      "status": "Confirmed by current source",
      "sourceName": "Nara City Tourism",
      "sourceUrl": "https://narashikanko.or.jp/event/detail_10227.html",
      "description": "",
      "tip": "",
      "priority": "normal",
      "includeInIcs": true,
      "isOngoing": false,
      "programTbd": false,
      "lastVerified": "2026-07-07"
    },
    {
      "id": "kofukuji-nanendo-daihannya",
      "title": "Kofuku-ji Nanendo: Daihannya-kyo Tendokue",
      "dateStart": "2026-10-17",
      "dateEnd": "2026-10-17",
      "city": "Nara",
      "area": "Nara Park",
      "venue": "Kofuku-ji Temple, Nanendo",
      "time": "Special viewing 9:00-17:00; ceremony 13:00",
      "category": "Temple / Shrine",
      "tags": [
        "temple",
        "Buddhist ritual",
        "special opening"
      ],
      "lgbtq": false,
      "cost": "Check source",
      "status": "Confirmed by current source",
      "sourceName": "Nara City Tourism",
      "sourceUrl": "https://narashikanko.or.jp/event/detail_10301.html",
      "description": "",
      "tip": "",
      "priority": "normal",
      "includeInIcs": true,
      "isOngoing": false,
      "programTbd": false,
      "lastVerified": "2026-07-07"
    },
    {
      "id": "kangoku-shrine-reitaisai",
      "title": "Kangoku Shrine Reitaisai Procession",
      "dateStart": "2026-10-17",
      "dateEnd": "2026-10-17",
      "city": "Nara",
      "area": "Nara city center",
      "venue": "Kangoku Shrine",
      "time": "10:00 procession listed",
      "category": "Traditional Festival",
      "tags": [
        "shrine",
        "procession",
        "festival"
      ],
      "lgbtq": false,
      "cost": "Free public viewing/check source",
      "status": "Confirmed by current source",
      "sourceName": "Nara City Tourism",
      "sourceUrl": "https://narashikanko.or.jp/event/detail_10346.html",
      "description": "",
      "tip": "",
      "priority": "normal",
      "includeInIcs": true,
      "isOngoing": false,
      "programTbd": false,
      "lastVerified": "2026-07-07"
    },
    {
      "id": "toshodaiji-shaka-nenbutsu",
      "title": "Toshodaiji Shaka Nenbutsu-e - Departure Day Option",
      "dateStart": "2026-10-21",
      "dateEnd": "2026-10-21",
      "city": "Nara",
      "area": "Nishinokyo",
      "venue": "Toshodaiji Temple",
      "time": "Begins Oct 21; continues after departure",
      "category": "Temple / Shrine",
      "tags": [
        "temple",
        "Buddhist ceremony",
        "departure day"
      ],
      "lgbtq": false,
      "cost": "Temple admission/check source",
      "status": "Confirmed by current source",
      "sourceName": "Nara City Tourism",
      "sourceUrl": "https://narashikanko.or.jp/event/detail_10228.html",
      "description": "Included as an optional departure-day item only because the trip leaves on Oct 21.",
      "tip": "",
      "priority": "optional",
      "includeInIcs": true,
      "isOngoing": false,
      "programTbd": false,
      "lastVerified": "2026-07-07"
    }
  ],
  "watchSources": [
    {
      "name": "Visit Gay Osaka events",
      "url": "https://visitgayosaka.com/event/",
      "why": "Official LGBTQ+ tourism site supported by Osaka tourism. Its events page had no October 2026 postings at verification time, so it is linked as a watch source rather than dated calendar items."
    },
    {
      "name": "Tsunagary Cafe Osaka schedule",
      "url": "https://tsunagary.jp/archives/category/schedule/osaka",
      "why": "LGBTQ+ community gatherings in Osaka/Kyoto/Kobe. At verification time, announced events only extended into summer 2026."
    },
    {
      "name": "EXPLOSION Osaka",
      "url": "https://explosion.osaka/en/",
      "why": "Doyama gay club with monthly parties. The live schedule at verification time showed July/August events, not October yet."
    },
    {
      "name": "Rainbow Festa official news",
      "url": "https://rainbowfesta.org/news?year=2026",
      "why": "Best place to watch for Pride booth, parade route, volunteer, and possible afterparty information."
    },
    {
      "name": "Kyodo Osaka October 2026 calendar",
      "url": "https://kyodo-osaka.co.jp/calendar/202610",
      "why": "Best month-level source for large concerts, theater, ballet, and arena events."
    },
    {
      "name": "eplus Osaka October 2026",
      "url": "https://eplus.jp/sf/event/month-10/kansai/osaka",
      "why": "Useful ticketing source for family shows, exhibitions, interactive experiences, and additional concerts."
    },
    {
      "name": "Billboard Live Osaka October 2026",
      "url": "https://www.billboard-live.com/osaka/schedules?month=2026-10-01",
      "why": "Best source for club-format jazz, pop, and international live acts in Umeda."
    },
    {
      "name": "Osaka Metro NiNE events",
      "url": "https://metronine.osaka/en/event/",
      "why": "Official/curated Osaka city events source to revisit closer to October."
    },
    {
      "name": "Nara official events calendar",
      "url": "https://narashikanko.or.jp/event/",
      "why": "Official Nara City source for temple/shrine schedule updates and access notes."
    }
  ],
  "omitted": [
    {
      "item": "USJ Halloween / Halloween Horror Nights 2026 specifics",
      "reason": "Searches found expected or third-party date estimates, but no official USJ 2026 Halloween announcement with confirmed dates at verification time."
    },
    {
      "item": "Nara Deer Antler Cutting 2026",
      "reason": "Official sources found during verification showed 2025 information and no confirmed 2026 October date, so it was not added."
    },
    {
      "item": "Kyoto Rainbow Pride 2026",
      "reason": "The 2026 Kyoto Pride event was in April, outside the Oct 9-21 trip window."
    },
    {
      "item": "Kyoto Jidai Matsuri / Kurama Fire Festival",
      "reason": "Major Kyoto festivals normally fall on Oct 22, after the stated Oct 21 departure, so they are not placed in the active trip calendar."
    },
    {
      "item": "Walkerplus 2025 pages",
      "reason": "Some pagination links led to 2025 listings. Those were intentionally ignored."
    }
  ]
}
